controllers/PageController.php
<?php

namespace app\controllers;

use app\models\File;
use app\models\Miniature;
use app\models\PageSearch;
use app\models\SimilarPage;
use Yii;
use app\models\Page;
use app\controllers\ParentController;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\UploadedFile;
use yii\helpers\Url;
use yii\imagine\Image;
use Imagine\Gd;
use Imagine\Image\Box;
use Imagine\Image\BoxInterface;
use yii\data\ActiveDataProvider;

use yii\web\Controller;

/**
 * PageController implements the CRUD actions for Page model.
 */
class PageController extends ParentController
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    public function actionFileUpdate()
    {
        $model = new File();

        $post = \Yii::$app->request->post();

        $model = File::findOne( $post['id'] );
        $model->title = $post['title'];

        $arrMess = array();
        $class = 'alert-success';

        if ($model->validate()) {
            // all inputs are valid
            $model->save();
            $class = 'alert-success';
            $arrMess []= [0=>'Сохранено'];
        } else {
            // validation failed: $errors is an array containing error messages
            $class = 'alert-danger';
            $arrMess = $model->errors;
        }

        return $this->renderPartial('@app/views/site/message_bootsrtap', [
            'class' => $class,
            'messages' => $arrMess,
        ]);
    }

    public function actionSimPageUpdate()
    {
        $model = new SimilarPage();

        $post = \Yii::$app->request->post();

        $model = SimilarPage::findOne( $post['id_record'] );
        $model->id_similar_page = $post['id_similar_page'];

        $arrMess = array();
        $class = 'alert-success';

        if ($model->validate()) {
            // all inputs are valid
            $model->save();
            $class = 'alert-success';
            $arrMess []= [0=>'Сохранено'];
        } else {
            // validation failed: $errors is an array containing error messages
            $class = 'alert-danger';
            $arrMess = $model->errors;
        }

        return $this->renderPartial('@app/views/site/message_bootsrtap', [
            'class' => $class,
            'messages' => $arrMess,
        ]);
    }

    public function actionSimPageDelete()
    {
        SimilarPage::findOne( Yii::$app->request->post()['id'] )->delete();
    }

    public function actionFileDelete()
    {
        File::findOne( Yii::$app->request->post()['id'] )->delete();
    }

    /**
     * Lists all Page models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new PageSearch();
        $dataProvider = $searchModel->search( Yii::$app->request->queryParams );

        return $this->render('index', [
            'dataProvider' => $dataProvider,
            'searchModel' =>  $searchModel,
        ]);
    }

    public static function prePageActions()
    {
        $arr = Yii::$app->request->post();
        if ( $arr  ) {
            $arr['Page']['date_event'] =  strtotime( $arr['Page']['date_event'] ) ;

            $vowels = array(" ", "/");
            $onlyconsonants = str_replace($vowels, "", $arr['Page']['url'] );
            $arr['Page']['url'] =   $onlyconsonants;
        }

        return  $arr;
    }

    /**
     * Creates a new Page model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Page();

        $arr = PageController::prePageActions();

        if ($model->load( $arr ) && $model->save()) {
            $this->filesAndSimPages($model);
            return Yii::$app->response->redirect(Url::to([ 'news/'.$model->url ]));
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Page model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        ParentController::deniedManagerPage($id);

        $model = $this->findModel($id);

        $arr = PageController::prePageActions();

        if ($model->load( $arr ) && $model->save()) {
            $this->filesAndSimPages($model);
            return Yii::$app->response->redirect(Url::to([ 'news/'.$model->url ]));
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Page model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        ParentController::deniedManagerPage($id);

        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }


    /**
     * Finds the Page model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Page the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Page::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    protected function filesAndSimPages($model)
    {
        $arr = Yii::$app->request->post();

        //
        $files = UploadedFile::getInstancesByName('filesLoad');

        //
        $image = UploadedFile::getInstanceByName('imageLoad');
        if ( $image )  {
            $oldFile = File::findOne(
                [
                    'group' => 'main_image',
                    'id_page' =>  $model->id
                ]
            );
            if ( $oldFile)  $oldFile->delete();
            $image->name = $model->title.'.'.explode(".", $image->name)[1];

            $files []=  $image;
        }

        //print_r(  $files );
        if ($files && count($files)>0 ) foreach ($files as $num => $file) {
            $fileNameAndEx = explode(".", $file->name);
            $unicNameFile = File::find()->count().'.'.$fileNameAndEx[1]; //уник номер и разрешение файла
            $path = 'files/'.$unicNameFile;
            $file->saveAs( $path );

            $fileUrlBool = File::checkUrl($path) ;

            $object = new File();
            $object->id_page = $model->id;
            $object->url = $path;
            $object->title = (  isset( $arr['title_file_load'][$num]) && $arr['title_file_load'][$num] !=''  ? $arr['title_file_load'][$num] : $fileNameAndEx[0] );
            if ($file == $image) $object->group = 'main_image';
            else $object->group = 'file';
            $object->img = $fileUrlBool;
            $object->save();

            if ( $fileUrlBool ) {
                $unicNameFile = Miniature::find()->count().'.'.$fileNameAndEx[1];
                $pathMini = 'miniatures/edit/'.$unicNameFile;
                Image::getImagine()->open(  $path )->thumbnail(new Box(30, 30))->save( $pathMini , ['quality' => 90]);
                $objectNew = new Miniature();
                $objectNew->url = $pathMini;
                $objectNew->group = 'edit';
                $objectNew->image_id = $object->id;
                $objectNew->save();

                $unicNameFile = Miniature::find()->count().'.'.$fileNameAndEx[1];
                $pathMini = 'miniatures/carusel/'.$unicNameFile;
                Image::getImagine()->open(  $path )->thumbnail(new Box(100, 100))->save( $pathMini , ['quality' => 90]);
                $objectNew = new Miniature();
                $objectNew->url = $pathMini;
                $objectNew->group = 'carusel';
                $objectNew->image_id = $object->id;
                $objectNew->save();
            }
        }
        /////

        ///
        if ( count( $arr['similar_pages'] ) > 0 ) foreach ($arr['similar_pages'] as $id_page) {
            $similarPageHas = SimilarPage::find()
                ->where(['id_page' =>  $arr['Page']['id_page'],'id_similar_page' => $id_page])
                ->count();

            if ($similarPageHas==0) {
                $similarPage = new SimilarPage();
                $similarPage->id_page = $model->id;
                $similarPage->id_similar_page = $id_page;
                $similarPage->save();
            }
        }
        ////
    }
}

controllers/SiteController.php
<?php

namespace app\controllers;

use app\models\Page;
use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;
use yii\helpers\Url;
use yii\web\NotFoundHttpException;
use yii\data\ActiveDataProvider;
use yii\helpers\Html;


class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
/*
if ($model->load(Yii::$app->request->post())) {
if ($model->validate()) {
    // form inputs are valid, do something here
return;
}
}
    */

    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        $session = Yii::$app->session;
        $dataProvider = new ActiveDataProvider([
            'query' => Page::find()->where(['active' => true]),
             'pagination' => [
                'pageSize' => $session->get('count_view'),
             ],
        ]);

        return $this->render('index',[
            'dataProvider' => $dataProvider,
        ]);
    }


    public static function getIdByUrl($url)
    {
         return Page::find()->where( ['url' =>
            str_replace("/news/", "", $url)
        ] )->select('id')->one()->id;
    }

    public function actionPage()
    {
        $id =  SiteController::getIdByUrl( Url::to('') );

        if (($model = Page::findOne($id)) !== null) {

            if ( $model->active == false
                && ParentController::checkAccAdminPanel() == false
            )
                throw new NotFoundHttpException('Страница не опубликована.');

            return $this->render('page', [
                'model' => $model,
            ]);
        } else {
            throw new NotFoundHttpException('Такой страницы не существует.');
        };
    }

    public function actionCountView()
    {
        $arr = Yii::$app->request->post();
        $session = Yii::$app->session;
        $session->set('count_view',  $arr['count_view'] );
        return Yii::$app->response->redirect( Url::home(true) );
    }

    public function actionUsers()
    {
        return $this->render('@app/views/user/index');
    }

    /**
     * Login action.
     *
     * @return Response|string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    /**
     * Logout action.
     *
     * @return Response
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return Response|string
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        }
        return $this->render('contact', [
            'model' => $model,
        ]);
    }

    /**
     * Displays about page.
     *
     * @return string
     */
    public function actionAbout()
    {
        return $this->render('about');
    }
}

views/site/about.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'About';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        This is the About page. You may modify the following file to customize its content:
    </p>

    <code><?= __FILE__ ?></code>
</div>

views/site/contact.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

$this->title = 'Contact';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>

    <?php if (Yii::$app->session->hasFlash('contactFormSubmitted')): ?>

        <div class="alert alert-success">
            Thank you for contacting us. We will respond to you as soon as possible.
        </div>

        <p>
            Note that if you turn on the Yii debugger, you should be able
            to view the mail message on the mail panel of the debugger.
            <?php if (Yii::$app->mailer->useFileTransport): ?>
                Because the application is in development mode, the email is not sent but saved as
                a file under <code><?= Yii::getAlias(Yii::$app->mailer->fileTransportPath) ?></code>.
                Please configure the <code>useFileTransport</code> property of the <code>mail</code>
                application component to be false to enable email sending.
            <?php endif; ?>
        </p>

    <?php else: ?>

        <p>
            If you have business inquiries or other questions, please fill out the following form to contact us.
            Thank you.
        </p>

        <div class="row">
            <div class="col-lg-5">

                <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

                    <?= $form->field($model, 'name')->textInput(['autofocus' => true]) ?>

                    <?= $form->field($model, 'email') ?>

                    <?= $form->field($model, 'subject') ?>

                    <?= $form->field($model, 'body')->textarea(['rows' => 6]) ?>

                    <?= $form->field($model, 'verifyCode')->widget(Captcha::className(), [
                        'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                    ]) ?>

                    <div class="form-group">
                        <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                    </div>

                <?php ActiveForm::end(); ?>

            </div>
        </div>

    <?php endif; ?>
</div>

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/index.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'My Yii Application';
?>
<div class="site-index">

    <div class="jumbotron">
        <h1>Congratulations!</h1>

        <p class="lead">You have successfully created your Yii-powered application.</p>

        <p><a class="btn btn-lg btn-success" href="http://www.yiiframework.com">Get started with Yii</a></p>
    </div>

    <div class="body-content">

        <label for="">Количество выводимых страниц: </label>
        <?
        $session = Yii::$app->session;

       // echo $session->get('count_view');
        //if ($session->has('count_view') == false ) $session->set('count_view', 1);

        $items = [
            '1' => '1',
            '10' => '10',
            '20'=>'20'
        ];
        $params = [
            'class' => 'count_view',
            'name' => 'count_view',
            'value' => $session->get('count_view'),
        ];
        echo Html::dropDownList('count_view', $session->get('count_view'), $items, $params);
        echo Html::button('Применить', ['class' => 'btn btn-primary btn-xs count_view_butt', 'style' =>'margin-left:10px']);
        ?>

        <?
        use yii\grid\GridView;
        use yii\helpers\Url;
        if ( $dataProvider ) {
            echo GridView::widget([
                'dataProvider' => $dataProvider,
                'columns' => [
                    ['class' => 'yii\grid\SerialColumn'],
                    [
                        'label' => 'Картинка',
                        'format' => 'raw',
                        'value' => function($data){
                            $main_page = \app\models\File::find()
                                ->where(['id_page' => $data->id])
                                ->andWhere(['=','group' , 'main_image'])
                                ->orderBy('id')
                                ->one();
                            if ( $main_page ) {
                                $miniature = \app\models\Miniature::find()
                                    ->where(['image_id' =>  $main_page->id])
                                    ->andWhere(['group' => 'edit'])
                                    ->one();

                                return Html::img(
                                    //Url::toRoute(
                                        $miniature->url
                                   // )
                                    ,[
                                    'alt'=>$main_page->title,
                                    'title'=>$main_page->title,
                                ]);
                            }
                        },
                    ],
                    [
                        'attribute' => 'title',
                        'label' => 'Заголовок',
                        'contentOptions' => function ($model, $key, $index, $column) {
                            return ['class' => 'name'];
                        },
                        'content' => function ($data) {
                            return Html::a($data->title, Url::to('/news/'.$data->url, true));
                        }
                    ],
                    'text_preview',
                ],
            ]);
        }
        ?>

    </div>
</div>


<?php
$this->registerJsFile('/js/codeMainPage.js',
    ['depends' => [\yii\web\JqueryAsset::className()]]);

?>

views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Login';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out the following fields to login:</p>

    <?php $form = ActiveForm::begin([
        'id' => 'login-form',
        'layout' => 'horizontal',
        'fieldConfig' => [
            'template' => "{label}\n<div class=\"col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
            'labelOptions' => ['class' => 'col-lg-1 control-label'],
        ],
    ]); ?>

        <?= $form->field($model, 'username')->textInput(['autofocus' => true]) ?>

        <?= $form->field($model, 'password')->passwordInput() ?>

        <?= $form->field($model, 'rememberMe')->checkbox([
            'template' => "<div class=\"col-lg-offset-1 col-lg-3\">{input} {label}</div>\n<div class=\"col-lg-8\">{error}</div>",
        ]) ?>

        <div class="form-group">
            <div class="col-lg-offset-1 col-lg-11">
                <?= Html::submitButton('Login', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
            </div>
        </div>

    <?php ActiveForm::end(); ?>

    <div class="col-lg-offset-1" style="color:#999;">
        You may login with <strong>admin/admin</strong> or <strong>demo/demo</strong>.<br>
        To modify the username/password, please check out the code <code>app\models\User::$users</code>.
    </div>
</div>

views/site/message_bootsrtap.php
<?php
use yii\helpers\Html;
$this->title = $name;
?>
<div class="alert   <?= $class  ?>">
    <?php
        foreach( $messages as $messageAr )
            foreach($messageAr as $message)
                echo $message ;
    ?>
</div>

views/site/page.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;
use yii\widgets\Breadcrumbs;


$anonim = Yii::$app->user->isGuest;

$this->title = $model->title;
$this->params['breadcrumbs'][] = $this->title;
    echo Breadcrumbs::widget([
        'itemTemplate' => "<li><i>{link}</i></li>\n", // template for all links
        'links' => [
            $model->title,
        ],
    ]);
?>
<?php
if( \app\controllers\ParentController::checkManagerPage($model->id) ) {
?>
    <?= Html::a('Редактировать', ['page/update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
<?php
}
?>
<div class="row">
    <div class = "col-md-12 col-sm-12 col-xs-12" >
         <h1><?= Html::encode($this->title) ?></h1>
        <?php
        $dataEv = $model->date_event ;
        if ( $dataEv && $dataEv != 0) {

            $dataEv = \app\models\Page::dateConvertTimespamp(  $dataEv );
        ?>
          <h5><i>Дата события: <?= $dataEv?></i></h5>
        <?php
        }
        ?>
    </div>

    <div class = "col-md-12 col-sm-12 col-xs-12" >
        <div class = "row" >

            <?php
            $classBlock = 'col-md-12 col-sm-12 col-xs-12';
            $images = '';
            $files = '';

            if ($anonim == false) {
                $images = '';

                $images = \app\models\File::find()
                    ->where(['id_page' => $model->id])
                    ->andWhere(['img' => true])
                    ->andWhere(['!=','group' , 'main_image'])
                    ->select(['url', 'title', 'id'])
                    ->all();

                $image = \app\models\File::find()
                    ->where(['id_page' => $model->id])
                    ->andWhere(['group' => 'main_image'])
                    ->select(['url', 'title', 'id'])
                    ->one();

                $sliderCheck = ( $images &&  $image);

                if (  $sliderCheck ) array_unshift($images,  $image);

                $files = \app\models\File::find()
                    ->where(['id_page' => $model->id])
                    ->andWhere(['img' => false])
                    ->select(['url', 'title'])
                    ->all();

                $similarPages = \app\models\SimilarPage::find()
                    ->where(['id_page' => $model->id])
                    ->select(['id_similar_page'])
                    ->all();

                if ($image || $images || $files ) $classBlock = 'col-md-6 col-sm-12 col-xs-12';
            }
            ?>

             <div class = "<?= $classBlock ?>">

                 <?php
                 $this->registerCssFile('/lightslider-master/src/css/lightslider.css');

                 $this->registerJsFile('/lightslider-master/src/js/lightslider.js',
                     ['depends' => [\yii\web\JqueryAsset::className()]]);

                 $this->registerCssFile('/colorbox-master/example1/colorbox.css');

                 $this->registerJsFile('/colorbox-master/jquery.colorbox.js',
                     ['depends' => [\yii\web\JqueryAsset::className()]]);

                 $this->registerJsFile('/js/codePage.js',
                     ['depends' => [\yii\web\JqueryAsset::className()]]);
                 ?>


                 <?php
                 use yii\helpers\Url;

                 if( $sliderCheck ==false && $image) {
                     ?>
                     <a href = " <?= Url::home(true).$image->url ?>" class ="colorbox" title = '<?=  $model->title ?>' >
                         <?= Html::img( Url::home(true).$image->url, [ 'title' => $model->title,'alt' => $model->title,'class' => "image_slider" ] )  ?>
                     </a>

                     <?php
                 }
                 ?>

                <?php
                if(  $images ) {
                    ?>

                    <div class = "col-md-12 col-sm-12 col-xs-12" >
                        <ul id="image-gallery" class="gallery list-unstyled cS-hidden">
                            <?php
                            foreach ($images as $image) {
                                $miniature = \app\models\Miniature::find()
                                ->where(['image_id' => $image->id])
                                ->andWhere( [ 'group' => 'carusel' ] )
                                ->one();
                                ?>
                                <li data-thumb="<?= Url::home(true).$miniature->url ?>">
                                    <a href = " <?= Url::home(true).$image->url ?>" class ="colorbox" title = ' <?=  $image->title ?>' >
                                        <?= Html::img( Url::home(true).$image->url, [ 'title' => $image->title,'alt' => $image->title,'class' => "image_slider" ] )  ?>
                                    </a>
                                </li>
                                <?php
                            }
                            ?>
                        </ul>
                    </div>

                    <?php
                }
                ?>


                <?php
                if(  $files ) {
                    ?>
                    <div class = "col-md-12 col-sm-12 col-xs-12" >
                        <h2>Файлы</h2>
                        <ul  class="">
                            <?php
                            foreach ( $files as $file) {
                                $miniature = \app\models\Miniature::find()
                                    ->where(['image_id' => $image->id])
                                    ->andWhere( [ 'group' => 'carusel' ] )
                                    ->one();
                                ?>
                                <li>
                                    <?= Html::a($file->title, [ $file->url], ['class' => 'profile-link', 'target'=>'_blank', 'title'=>$file->title ])   ?>
                                </li>
                                <?php
                            }
                            ?>
                        </ul>
                    </div>
                    <?php
                }
                ?>


                 <?php
                 if(   $similarPages ) {
                     ?>
                     <div class = "col-md-12 col-sm-12 col-xs-12" >
                         <h2>Похожие страницы</h2>
                         <ul  class="">
                             <?php
                             foreach (   $similarPages as $similarPage ) {
                                 $similarPage = \app\models\Page::find()
                                     ->where(['id' =>  $similarPage->id_similar_page])
                                     ->andWhere( [ 'active' => true ] )
                                     ->select(['title','url'])
                                     ->one();
                                 ?>
                                 <li>
                                     <?= Html::a($similarPage->title, [ '/news/'.$similarPage->url], ['class' => 'profile-link', 'target'=>'_blank', 'title'=>$similarPage->title ])   ?>
                                 </li>
                                 <?php
                             }
                             ?>
                         </ul>
                     </div>
                     <?php
                 }
                 ?>

             </div>



            <div class = "<?= $classBlock ?>" >
                <?
                if ( $anonim ) {
                    echo $model->text_preview;
                    echo '<br>';
                    echo '<br>';
                    echo Html::tag('div', 'Авторизируйтесь, что бы увидеть полную версию страницы.', ['class' => ['alert', 'alert-warning']] );
                }
                else echo $model->text;
                ?>
            </div>

         </div>
    </div>
</div>