controllers/PageController.php
<?php

namespace app\controllers;

use app\models\File;
use app\models\Miniature;
use app\models\PageSearch;
use app\models\SimilarPage;
use Yii;
use app\models\Page;
use app\controllers\ParentController;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\UploadedFile;
use yii\helpers\Url;
use yii\imagine\Image;
use Imagine\Gd;
use Imagine\Image\Box;
use Imagine\Image\BoxInterface;
use yii\data\ActiveDataProvider;

use yii\web\Controller;

/**
 * PageController implements the CRUD actions for Page model.
 */
class PageController extends ParentController
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    public function actionFileUpdate()
    {
        $model = new File();

        $post = \Yii::$app->request->post();

        $model = File::findOne( $post['id'] );
        $model->title = $post['title'];

        $arrMess = array();
        $class = 'alert-success';

        if ($model->validate()) {
            // all inputs are valid
            $model->save();
            $class = 'alert-success';
            $arrMess []= [0=>'Сохранено'];
        } else {
            // validation failed: $errors is an array containing error messages
            $class = 'alert-danger';
            $arrMess = $model->errors;
        }

        return $this->renderPartial('@app/views/site/message_bootsrtap', [
            'class' => $class,
            'messages' => $arrMess,
        ]);
    }

    public function actionSimPageUpdate()
    {
        $model = new SimilarPage();

        $post = \Yii::$app->request->post();

        $model = SimilarPage::findOne( $post['id_record'] );
        $model->id_similar_page = $post['id_similar_page'];

        $arrMess = array();
        $class = 'alert-success';

        if ($model->validate()) {
            // all inputs are valid
            $model->save();
            $class = 'alert-success';
            $arrMess []= [0=>'Сохранено'];
        } else {
            // validation failed: $errors is an array containing error messages
            $class = 'alert-danger';
            $arrMess = $model->errors;
        }

        return $this->renderPartial('@app/views/site/message_bootsrtap', [
            'class' => $class,
            'messages' => $arrMess,
        ]);
    }

    public function actionSimPageDelete()
    {
        SimilarPage::findOne( Yii::$app->request->post()['id'] )->delete();
    }

    public function actionFileDelete()
    {
        File::findOne( Yii::$app->request->post()['id'] )->delete();
    }

    /**
     * Lists all Page models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new PageSearch();
        $dataProvider = $searchModel->search( Yii::$app->request->queryParams );

        return $this->render('index', [
            'dataProvider' => $dataProvider,
            'searchModel' =>  $searchModel,
        ]);
    }

    public static function prePageActions()
    {
        $arr = Yii::$app->request->post();
        if ( $arr  ) {
            $arr['Page']['date_event'] =  strtotime( $arr['Page']['date_event'] ) ;

            $vowels = array(" ", "/");
            $onlyconsonants = str_replace($vowels, "", $arr['Page']['url'] );
            $arr['Page']['url'] =   $onlyconsonants;
        }

        return  $arr;
    }

    /**
     * Creates a new Page model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Page();

        $arr = PageController::prePageActions();

        if ($model->load( $arr ) && $model->save()) {
            $this->filesAndSimPages($model);
            return Yii::$app->response->redirect(Url::to([ 'news/'.$model->url ]));
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Page model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        ParentController::deniedManagerPage($id);

        $model = $this->findModel($id);

        $arr = PageController::prePageActions();

        if ($model->load( $arr ) && $model->save()) {
            $this->filesAndSimPages($model);
            return Yii::$app->response->redirect(Url::to([ 'news/'.$model->url ]));
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Page model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        ParentController::deniedManagerPage($id);

        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }


    /**
     * Finds the Page model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Page the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Page::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    protected function filesAndSimPages($model)
    {
        $arr = Yii::$app->request->post();

        //
        $files = UploadedFile::getInstancesByName('filesLoad');

        //
        $image = UploadedFile::getInstanceByName('imageLoad');
        if ( $image )  {
            $oldFile = File::findOne(
                [
                    'group' => 'main_image',
                    'id_page' =>  $model->id
                ]
            );
            if ( $oldFile)  $oldFile->delete();
            $image->name = $model->title.'.'.explode(".", $image->name)[1];

            $files []=  $image;
        }

        //print_r(  $files );
        if ($files && count($files)>0 ) foreach ($files as $num => $file) {
            $fileNameAndEx = explode(".", $file->name);
            $unicNameFile = File::find()->count().'.'.$fileNameAndEx[1]; //уник номер и разрешение файла
            $path = 'files/'.$unicNameFile;
            $file->saveAs( $path );

            $fileUrlBool = File::checkUrl($path) ;

            $object = new File();
            $object->id_page = $model->id;
            $object->url = $path;
            $object->title = (  isset( $arr['title_file_load'][$num]) && $arr['title_file_load'][$num] !=''  ? $arr['title_file_load'][$num] : $fileNameAndEx[0] );
            if ($file == $image) $object->group = 'main_image';
            else $object->group = 'file';
            $object->img = $fileUrlBool;
            $object->save();

            if ( $fileUrlBool ) {
                $unicNameFile = Miniature::find()->count().'.'.$fileNameAndEx[1];
                $pathMini = 'miniatures/edit/'.$unicNameFile;
                Image::getImagine()->open(  $path )->thumbnail(new Box(30, 30))->save( $pathMini , ['quality' => 90]);
                $objectNew = new Miniature();
                $objectNew->url = $pathMini;
                $objectNew->group = 'edit';
                $objectNew->image_id = $object->id;
                $objectNew->save();

                $unicNameFile = Miniature::find()->count().'.'.$fileNameAndEx[1];
                $pathMini = 'miniatures/carusel/'.$unicNameFile;
                Image::getImagine()->open(  $path )->thumbnail(new Box(100, 100))->save( $pathMini , ['quality' => 90]);
                $objectNew = new Miniature();
                $objectNew->url = $pathMini;
                $objectNew->group = 'carusel';
                $objectNew->image_id = $object->id;
                $objectNew->save();
            }
        }
        /////

        ///
        if ( count( $arr['similar_pages'] ) > 0 ) foreach ($arr['similar_pages'] as $id_page) {
            $similarPageHas = SimilarPage::find()
                ->where(['id_page' =>  $arr['Page']['id_page'],'id_similar_page' => $id_page])
                ->count();

            if ($similarPageHas==0) {
                $similarPage = new SimilarPage();
                $similarPage->id_page = $model->id;
                $similarPage->id_similar_page = $id_page;
                $similarPage->save();
            }
        }
        ////
    }
}

views/page/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
/////////
//use kartik\select2\Select2;
use yii\web\JsExpression;
use app\models\Page;
use kartik\datetime\DateTimePicker;
use kartik\date\DatePicker;
use dosamigos\ckeditor\CKEditor;
use kartik\checkbox\CheckboxX;
use yii\helpers\ArrayHelper;
use yii\widgets\Pjax;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $model app\models\Page */
/* @var $form yii\widgets\ActiveForm */
?>


<div class="page-form">

    <?= Html::hiddenInput('id_page', $model->id,  ['class' => 'id_page_hid']) ?>



    <?php $form = ActiveForm::begin( [ 'options'=>['enctype'=>'multipart/form-data'] ] ); ?>

    <?= $form->field($model, 'title')->textInput(['maxlength' => true]) ?>

    <?=
    '<label class="control-label" for="active">Опубликновано</label>'.
     CheckboxX::widget([
        'model' => $model,
        'attribute' => 'active',
         //'value'=>0,
        'pluginOptions' => [
            'threeState' => false
        ]
     ])
    ?>

    <?= $form->field($model, 'url')->textInput(['maxlength' => true]) ?>

    <?
    $objects = \dektrium\user\models\User::find()->all();

    if ($objects) {
        $items = ArrayHelper::map($objects, 'id', 'username');


        $params = [
            'prompt' => 'По-умолчанию автором будет создатель страницы.',
            'class' => 'select2activ'
        ];
        echo $form->field($model, 'author')->dropDownList($items,$params);
    }
    ?>

    <label for="">Картинка</label>
    <?
    $image =  \app\models\File::find()
        ->where(['id_page' => $model->id])
        ->andWhere(['group' => 'main_image'])
        ->one();
    ?>
    <?
    if (  $image ) {
        ?>
        <?
        $miniature = \app\models\Miniature::find()
            ->where(['image_id' => $image->id])
            ->andWhere(['group' => 'edit'])
            ->one();
        ?>
        <div>
            <a href = " <?= Url::home(true).$image->url ?>" class ="colorbox" title = ' <?=  $image->title ?>' >
                <?= Html::img( Url::home(true).'/'.$miniature->url, ['title' => $image->title,'alt' => $image->title]) ?>
            </a>
        </div>
        <?
        ?>
        <?
    }
    ?>
    </br>
    <div class = "">
            <?= Html::fileInput('imageLoad', '',  ['class' => 'file']) ?>
            <br>
    </div>
    <br>



    <label for="">Файлы</label>
    <?
     $files = \app\models\File::find()
    ->where(['id_page' => $model->id])
    ->andWhere(['!=','group' , 'main_image'])
    ->orderBy('id')
    ->all();
    if ($files) {
    ?>
        <?
        foreach( $files as $file) {
        ?>
        <div class = "file" data-id-file = '<?= $file->id ?>'>

            <?
            if ( $file->img  ) {
                $miniature = \app\models\Miniature::find()
                    ->where(['image_id' => $file->id])
                    ->andWhere(['group' => 'edit'])
                    ->one();
                ?>
                <a href = " <?= Url::home(true).$file->url ?>" class ="colorbox" title = ' <?=  $file->title ?>' >
                    <?= Html::img( Url::home(true).'/'.$miniature->url, ['title' => $file->title,'alt' => $file->title]) ?>
                </a>
                <?
            } else
                echo Html::a($file->title, [ $file->url], ['class' => 'profile-link', 'target'=>'_blank', 'title'=>$file->title ]);
            ?>

            <?= Html::textInput('title_file_upload', $file->title,  ['class' => 'title_file_upload', 'placeholder'=>'Имя файла']) ?>

            <?=  Html::tag('div', 'Обновить', ['class' => ['btn', 'btn-primary update-file']]); ?>
            <?=  Html::tag('div', 'Удалить', ['class' => ['btn', 'btn-danger del-file']]); ?>

            <div class = "messages"></div>

        </div>
         <br>
        <?
        }
        ?>
    <?
    }
    ?>

    <br>
    <br>
    <div class = "filesLoadContainer">
        <div class = "fileLoadForm">
            <?= Html::textInput('title_file_load[]', '',  ['class' => '', 'placeholder'=>'Имя файла']) ?>
            <?= Html::fileInput('filesLoad[]', '',  ['class' => 'file']) ?>
            <br>
        </div>
    </div>
    <?=  Html::tag('div', 'Ещё файл', ['class' => ['btn', 'btn-success add_file']]); ?>
    <br>
    <br>
    <br>


    <label for="">Похожие страницы</label>
    <?
    $objects = Page::find()
        ->where(['!=', 'id', $model->id])
        ->all();

    $items = ArrayHelper::map($objects, 'id', 'title');

    $similarPages = \app\models\SimilarPage::find()
        ->where(['id_page' => $model->id])
        ->all();
    if ( $similarPages )  {
        ?>
        <label for="">Похожие страницы</label>
        <br>
        <div class="similarSubPageContainer">
            <?
            foreach ($similarPages as $similarPage) {
                ?>
                <div class="similarSubPage" data-id-sim-page='<?= $similarPage->id ?>'>
                    <?
                    echo Html::dropDownList('similar_pages_sub[]', $similarPage->id_similar_page,
                        $items, ['class' => 'similar_pages select2activ']
                    );

                    echo Html::tag('div', 'Обновить', ['class' => ['btn', 'btn-primary update_sim_page']]);
                    echo Html::tag('div', 'Удалить', ['class' => ['btn', 'btn-danger del_sim_page']]);
                    ?>
                    <div class="messages"></div>
                    <br>
                </div>
                <?
            }
            ?>
        </div>
        <?
    }
    ?>

    <div class="similarPageContainer">
        <?
        if ($objects) {


            $params = [
                'prompt' => 'Выберите родительскую страницу',
                'class' => 'select2activ'
            ];

            echo 'Добавить<br>';
            echo '<br>';

            echo Html::dropDownList('similar_pages[]', null,
                $items, ['class' => 'similar_pages select2activ', 'prompt' => 'Выберите страницу']
            );
        }
        ?>
    </div>
    <br>
    <?= Html::tag('div', 'Ещё страницу', ['class' => ['btn', 'btn-success add_page']]); ?>
    <br>
    <br>


    <?= $form->field($model, 'text_preview')->textInput(['maxlength' => true]) ?>

    <?=
    $form->field($model, 'text')->widget(CKEditor::className(), [
        'options' => ['rows' => 6],
        'preset' => 'full'
    ])
    ?>

    <label for="">Дата события</label>
    <?

    echo DateTimePicker::widget([
        'name' => 'Page[date_event]',
        'value' =>  Page::dateConvertTimespamp( $model->date_event ),
        'pluginOptions' => [
            'autoclose' => true,
            'format' =>  Page::getDateFormatForWidjet()
        ]
    ]);
    ?>

    <br>
    <br>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

<?php
    $this->registerCssFile('/select2-master/dist/css/select2.css');

    $this->registerJsFile('/select2-master/dist/js/select2.js',
        ['depends' => [\yii\web\JqueryAsset::className()]]);

    $this->registerJsFile('/js/livequery.js',
    ['depends' => [\yii\web\JqueryAsset::className()]]);

    $this->registerCssFile('/colorbox-master/example1/colorbox.css');

    $this->registerJsFile('/colorbox-master/jquery.colorbox.js',
    ['depends' => [\yii\web\JqueryAsset::className()]]);

    $this->registerJsFile('/js/code.js',
    ['depends' => [\yii\web\JqueryAsset::className()]]);
?>

views/page/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Page */

$this->title = 'Create Page';
$this->params['breadcrumbs'][] = ['label' => 'Pages', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="page-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/page/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use app\models\Page;

/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */


$this->title = 'Pages';
$this->params['breadcrumbs'][] = $this->title;



?>

<div class="page-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Create Page', ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'tableOptions' => [
            'class' => 'table table-striped table-bordered'
        ],
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],
            'title',
            [
                'attribute'=>'author',
                'label'=>'Автор',
                'format'=>'text', // Возможные варианты: raw, html
                'content'=>function($data){
                    return $data->user->username;
                },
                'filter' => Page::getUsersList()
            ],
            [
                'filter' => Page::getStatusesArray(),
                'attribute' => 'active',
                'format' => 'raw',
                'value' => function ($model, $key, $index, $column) {
                   return $model->getStatus();
                }
            ],
            [
                'attribute' => 'created_at',
                'format' =>  ['date', 'Y-MM-dd HH:mm:ss' ],
                'options' => ['width' => '200']
            ],
            [
                'class' => 'yii\grid\ActionColumn',

                'buttons' => [
                    'view' => function ($url,$model) {
                        return Html::a(
                            '<span class="glyphicon glyphicon-eye-open"></span>',
                            '/news/'.$model->url);
                    },
                ],
            ],
        ],
    ]); ?>
</div>

views/page/update.php
<?php

use yii\helpers\Html;
use yii\widgets\Breadcrumbs;

/* @var $this yii\web\View */
/* @var $model app\models\Page */

$this->title = 'Update Page: ' . $model->title;

echo Breadcrumbs::widget([
    'itemTemplate' => "<li><i>{link}</i></li>\n", // template for all links
    'links' => [
        [
            'label' => 'Pages',
            'url' => ['/page/index'],
            'template' => "<li>{link}</li>\n", // template for this link only
        ],
        [
            'label' => $model->title,
            'url' => ['/news/'.$model->url],
            'template' => "<li>{link}</li>\n", // template for this link only
        ],
        'Edit',
    ],
]);
?>
<div class="page-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/page/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;
use yii\widgets\Breadcrumbs;
use  app\controllers\ParentController;

/* @var $this yii\web\View */
/* @var $model app\models\Page */

$this->title = $model->title;

echo Breadcrumbs::widget([
        'itemTemplate' => "<li><i>{link}</i></li>\n", // template for all links
        'links' => [
            [
                'label' => 'Pages',
                'url' => ['/page/index'],
                'template' => "<li>{link}</li>\n", // template for this link only
            ],
            $model->title,
        ],
    ]);
?>
<div class="page-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['page/update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['page/delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'title',
            'url:url',
            'image',
            'text_preview',
            'text:ntext',
            'active',
            'created_at',
            'updated_at',
        ],
    ]);
    ?>

</div>